name: PandocConvert

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - pages/cv.md

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: mkdir output
      - uses: maxheld83/pandoc@v2

      - uses: docker://pandoc/latex:2.9
        with:
          args: "--standalone --output=output/cv.pdf pages/cv.md"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
